### ISSUE TITLE
Add Image to Readme

### ISSUE THREAD

**Issue by JaiminShimpi** [Sneh-Trivedi/Home-Price-Analysis-and-Prediction#3]
Add those sample images into Readme.MD as a source. Follow the below code:
<img src=".../image_folder/image" width="100"/>
View it in raw of code not visible

**Comment by Sneh-Trivedi** [comment]
I've updated the Readme file. Kindly have a look !!

**Comment by JaiminShimpi** [comment]
Ok. Brother
